"use client";

import { useState } from "react";
import { Bell, BookOpen, CalendarDays, ChevronDown, ChevronRight, Compass, FileText, GraduationCap, LayoutDashboard, Menu, MessageSquare, Search, Settings, ShieldCheck, X } from "lucide-react";

const nav = [[LayoutDashboard,"Overview"],[BookOpen,"My Credits"],[Compass,"Discover"],[CalendarDays,"Events"],[FileText,"Certificates"],[ShieldCheck,"APC Status"]] as const;
const workspace = [[GraduationCap,"Learning Hub"],[MessageSquare,"Messages"],[Settings,"Settings"]] as const;
const categories = [["A","Educational Activities","4 / 6",67,"#3b82f6"],["B","Reviewing Performance","3 / 4",75,"#16a56b"],["C","Measuring Outcomes","2 / 3",67,"#f59e0b"],["D","Professional Leadership","1 / 4",25,"#8b5cf6"],["E","Cultural Safety & Equity","2 / 3",67,"#f43f5e"]];
const events = [["Australasian Clinical Update 2026","18 May · Auckland","4 CPD points","sky"],["Digital Dentistry Masterclass","24 May · Online","2 CPD points","mint"],["Antimicrobial Stewardship Forum","03 Jun · Wellington","3 CPD points","coral"]];
function Mark(){return <span className="care-mark"><i/><b/></span>}; function Avatar(){return <span className="avatar">SC</span>}
export default function Home(){const [open,setOpen]=useState(false);const [notice,setNotice]=useState(true);return <div className="app-shell">
<aside className={open?"sidebar sidebar-open":"sidebar"}><div className="brand"><Mark/><div><strong>Care Credits</strong><small>Log points. Renew licence. Focus on patients.</small></div><button className="close-nav" onClick={()=>setOpen(false)}><X/></button></div><nav>{nav.map(([I,n])=><button className={n==="Overview"?"nav-item active":"nav-item"} key={n}><I/><span>{n}</span></button>)}</nav><div className="nav-rule"/><p className="nav-heading">WORKSPACE</p><nav>{workspace.map(([I,n])=><button className="nav-item" key={n}><I/><span>{n}</span></button>)}</nav><div className="profile"><Avatar/><div><strong>Dr. Sarah Chen</strong><small>General Practice</small></div><ChevronRight/></div></aside>
{open&&<button className="veil" onClick={()=>setOpen(false)} aria-label="Close navigation"/>}<main className="main"><header className="topbar"><button className="menu-button" onClick={()=>setOpen(true)} aria-label="Open navigation"><Menu/></button><label className="search"><Search/><input placeholder="Search conferences, webinars, workshops..."/></label><div className="top-actions"><button className="icon-button" onClick={()=>setNotice(!notice)} aria-label="Notifications"><Bell/>{notice&&<i/>}</button><Avatar/><ChevronDown className="chevron"/></div></header>
<div className="content"><section className="hero"><div className="hero-copy"><span className="eyebrow">APC 2026</span><h1>Your APC Renewal Progress</h1><p>Track CPD points, monitor compliance, and discover accredited learning opportunities.</p></div><div className="progress-panel"><div className="ring"><span>60%</span></div><div className="progress-copy"><h2>12 / 20 <span>CPD Points Earned</span></h2><p><CalendarDays/> APC Renewal Deadline<br/><strong>30 Jun 2026</strong></p><em>48 days remaining</em><b className="warning">⚠ &nbsp;8 points required before renewal</b></div><button className="primary">Find eligible events <ChevronRight/></button></div></section>
<section className="metrics"><Metric icon="★" title="Points earned" value="12" tone="green"/><Metric icon="◎" title="Points remaining" value="8" tone="orange"/><Metric icon="♢" title="Compliance" value="On track" detail="60% complete" tone="blue"/></section>
<div className="dashboard-grid"><div className="left-column"><section className="card"><div className="card-heading"><div><span className="heading-icon">◔</span><h2>CPD category breakdown</h2></div><p>Annual target <strong>20 pts</strong></p></div><div className="category-content"><div className="donut"><div><strong>12 / 20</strong><span>CPD Points<br/>Earned</span></div></div><div className="category-list"><div className="category-labels"><span>Category</span><span>Earned / Limit</span><span>% of limit</span></div>{categories.map(([a,b,c,d,e])=><div className="category-row" key={a}><span className="category-name"><i style={{background:e}}/>{a} - {b}</span><span>{c}</span><span>{d}%</span><div className="bar"><i style={{width:`${d}%`,background:e}}/></div></div>)}</div></div></section>
<section className="card"><div className="card-heading"><div><span className="heading-icon">▣</span><h2>Upcoming events</h2></div><button className="text-link">View all events <ChevronRight/></button></div>{events.map(([a,b,c,d])=><button className="event" key={a}><span className={`event-photo ${d}`}/><span className="event-name"><strong>{a}</strong><small>{b}</small></span><span className="event-points">{c}</span><ChevronRight/></button>)}</section></div>
<div className="right-column"><section className="card"><div className="card-heading"><div><span className="heading-icon">✦</span><h2>Recommended for you</h2></div><button className="text-link">See all <ChevronRight/></button></div><Recommendation title="Women’s Health Update" provider="Medsafe Learning" points="3 points" format="Hybrid" match="94%" type="doctor"/><Recommendation title="AI in Primary Care" provider="HealthEd" points="2 points" format="Online" match="88%" type="speaker"/></section><section className="card"><div className="card-heading"><div><span className="heading-icon">♧</span><h2>APC compliance assistant</h2></div></div><div className="assistant-content"><div className="score"><strong>60</strong><span>Compliance<br/>score</span></div><div><p>Predicted readiness: <strong className="success">92%</strong></p><p className="missing">Missing categories: D, E</p><button className="text-link">Review action plan <ChevronRight/></button></div></div></section></div></div></div></main></div>}
function Metric({icon,title,value,detail,tone}:{icon:string,title:string,value:string,detail?:string,tone:string}){return <article className="metric"><span className={`metric-icon ${tone}`}>{icon}</span><div><p>{title}</p><strong className={tone==="green"?"metric-green":""}>{value}</strong>{detail&&<small>{detail}</small>}</div></article>}
function Recommendation({title,provider,points,format,match,type}:{title:string,provider:string,points:string,format:string,match:string,type:string}){return <article className="recommendation"><div className={`rec-photo ${type}`}/><div><h3>{title}</h3><p>{provider}</p><small>♢ &nbsp;{points} &nbsp;&nbsp;▣ &nbsp;{format}</small></div><div className="match">{match}<span>match</span></div><button className="more">⋮</button></article>}
